name: build-workflow
'on':
  pull_request: {}
  workflow_dispatch: {}
concurrency: '1'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
        id: Checkout
      - name: Install Dependencies
        run: yarn install --immutable
        id: Install
      - name: Build
        run: yarn build
        id: Build
